name: Deploy

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Clean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: 22
        KEY: ${{ secrets.SSHKEY }}
        script: 'rm -rf /home/devops/projects/devops-demo'

    - name: Copy 
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: 22
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "/home/devops/projects/devops-demo"

    - name: mvn install 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: 22
        KEY: ${{ secrets.SSHKEY }}
        script: 'cd /home/devops/projects/devops-demo && mvn install'

    - name: Restart
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: 22
        KEY: ${{ secrets.SSHKEY }}
        script: 'systemctl restart spring1'